In [8]:
import numpy as np
import pandas as pd

In [10]:
df = pd.read_csv("../data/spam.csv",encoding="latin-1")

In [11]:
df.sample(5)

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
4069,ham,Ok i wont call or disturb any one. I know all ...,NaN,NaN,NaN
212,ham,K:)k:)good:)study well.,NaN,NaN,NaN
567,ham,"So anyways, you can just go to your gym or wha...",NaN,NaN,NaN
4907,ham,"I'm in solihull, | do you want anything?",NaN,NaN,NaN
1107,ham,From someone not to smoke when every time I've...,NaN,NaN,NaN

In [12]:
df.shape

(5572, 5)

## DATA CLEANING

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   str
 1   v2          5572 non-null   str
 2   Unnamed: 2  50 non-null     str
 3   Unnamed: 3  12 non-null     str
 4   Unnamed: 4  6 non-null      str
dtypes: str(5)
memory usage: 217.8 KB

In [14]:
df.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'],inplace=True)

In [15]:
df.sample(5)

        v1                                                 v2
2070  spam  Sexy Singles are waiting for you! Text your AG...
3204   ham  Oh, yes, I've just been a little under the wea...
2036   ham  You can jot down things you want to remember l...
4572  spam  \URGENT! This is the 2nd attempt to contact U!...
892    ham  Nutter. Cutter. Ctter. Cttergg. Cttargg. Ctarg...

In [16]:
# Renaming the columns

df.rename(columns={'v1':'target','v2':"text"},inplace=True)

In [17]:
df

     target                                               text
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham              Will Ì_ b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [18]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()