In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

In [16]:
pd.set_option("display.max_columns",None)
pd.set_option("display.float_format",lambda x: f"{x: .3f}")
sns.set_theme(style="darkgrid")
plt.rcParams.update(
    {
        'axes.titlesize':10,
        "axes.labelsize":9,
        "xtick.labelsize":8,
        "ytick.labelsize":8
    }
)
RANDOM_STATE=42
DATASET_PATH="../data/Online Retail.csv"

In [17]:
df=pd.read_csv(DATASET_PATH)

In [20]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.550,17850.000,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.390,17850.000,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.750,17850.000,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.390,17850.000,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.390,17850.000,United Kingdom

In [23]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [21]:
df.shape

(541909, 8)

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

In [24]:
df.describe()

         Quantity   UnitPrice  CustomerID
count  541909.000  541909.000  406829.000
mean        9.552       4.611   15287.691
std       218.081      96.760    1713.600
min    -80995.000  -11062.060   12346.000
25%         1.000       1.250   13953.000
50%         3.000       2.080   15152.000
75%        10.000       4.130   16791.000
max     80995.000   38970.000   18287.000